modLoader="javafml"
loaderVersion="[44,)"
license="GNU General Public License 3.0"
issueTrackerURL="https://github.com/MrCrayfish/GoldenHopper/issues"

[[mods]]
modId="goldenhopper"
version="1.2.8"
displayName="Golden Hopper"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=goldenhopper"
displayURL="https://mrcrayfish.com/mods?id=goldenhopper"
logoFile="goldenhopper.png"
credits="@Moonshiner99 on Twitter for the mod idea. Pois1x for improved textures!"
authors="MrCrayfish"
description="Simply adds a new golden hopper variant that can filter items, nothing more!"

[[dependencies.goldenhopper]]
    modId="forge"
    mandatory=true
    versionRange="[44.0.36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.goldenhopper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"

[modproperties.goldenhopper]
    catalogueItemIcon="goldenhopper:golden_hopper"
    configuredBackground="minecraft:textures/block/gold_ore.png"
